<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE questions [
    <!ELEMENT questions (Question+)>
    <!ELEMENT Question (question, option1, option2, option3, answerNr, solution)>
    <!ELEMENT question (#PCDATA)>
    <!ATTLIST question name ID #REQUIRED>

    <!ELEMENT option1 (#PCDATA)>
    <!ATTLIST option1 translatable CDATA #IMPLIED>
    <!ATTLIST option1 name ID #REQUIRED>

    <!ELEMENT option2 (#PCDATA)>
    <!ATTLIST option2 name ID #REQUIRED>
    <!ATTLIST option2 translatable CDATA #IMPLIED>

    <!ELEMENT option3 (#PCDATA)>
    <!ATTLIST option3 name ID #REQUIRED>
    <!ATTLIST option3 translatable CDATA #IMPLIED>

    <!ELEMENT answerNr (#PCDATA)>

    <!ELEMENT solution (#PCDATA)>
    <!ATTLIST solution translatable CDATA #IMPLIED>
    ]>

<questions>
    <Question>
        <question name="quiz_question_1">What faculty is the BINFO program part of?</question>
        <option1 name="quiz_1_1">Faculty of Law, Economics and Finance</option1>
        <option2 name="quiz_1_2">Faculty of Science, Technology and Medecine</option2>
        <option3 name="quiz_1_3">Faculty of Humanities, Education and Social Sciences</option3>
        <answerNr>2</answerNr>
        <solution>BINFO program is part of the Faculty of Science, Technology and Medecine.</solution>
    </Question>

    <Question>
        <question name="quiz_question_2">What does BINFO's letters stand for?</question>

        <option1 name="quiz_2_1">Bachelor Information</option1>
        <option2 name="quiz_2_2">Bachelor en Informatique</option2>
        <option3 name="quiz_2_3">Bachelor in Applied Information Technology</option3>
        <answerNr>2</answerNr>
        <solution>Bachelor en INFOrmatique, those capital letters make BINFO.</solution>
    </Question>

    <Question>
        <question name="quiz_question_3">What program does BINFO actually represent?</question>

        <option1 name="quiz_3_1">Bachelor in Applied Information Technology</option1>
        <option2 name="quiz_3_2">Bachelor in Computer Sciences</option2>
        <option3 name="quiz_3_3">Bachelor en Informatique</option3>
        <answerNr>1</answerNr>
        <solution>There's a trap. The program changed its name during year 2019-2020 but the initials remained the same.</solution>
    </Question>

    <Question>
        <question name="quiz_question_4">How many semesters does the BINFO program contain?
        </question>

        <option1 name="quiz_4_1" translatable="false">3</option1>
        <option2 name="quiz_4_2" translatable="false">4</option2>
        <option3 name="quiz_4_3" translatable="false">6</option3>
        <answerNr>3</answerNr>
        <solution>60 ECTS during 3 years which makes a total of 180 ECTS at the end of the Bachelor.</solution>
    </Question>

    <Question>
        <question name="quiz_question_5">How many ECTS is needed to a re-enrollment?</question>

        <option1 name="quiz_5_1" translatable="false">30</option1>
        <option2 name="quiz_5_2" translatable="false">45</option2>
        <option3 name="quiz_5_3" translatable="false">0</option3>
        <answerNr>1</answerNr>
        <solution>You'll need to validate at least 30 ECTS in the first school year. Of course, you can still retake the failed exam later in your studies.</solution>
    </Question>

    <Question>
        <question name="quiz_question_6">Where do BINFO students have class?</question>

        <option1 name="quiz_6_1">Only belval</option1>
        <option2 name="quiz_6_2">Belval and Kirchberg</option2>
        <option3 name="quiz_6_3">Only Kirchberg</option3>
        <answerNr>1</answerNr>
        <solution>It used to be both in Belval and Kirchberg, back in the days.</solution>
    </Question>

    <Question>
        <question name="quiz_question_7">During which semester do you need to go on mobility?
        </question>

        <option1 name="quiz_7_1">1st or 2nd</option1>
        <option2 name="quiz_7_2">3rd or 4th</option2>
        <option3 name="quiz_7_3">5th or 6th</option3>
        <answerNr>2</answerNr>
        <solution>The first year is a bit soon and you are already doing a internship in the last year so only option is during the second year.</solution>
    </Question>

    <Question>
        <question name="quiz_question_8">What skills do you need before even enrolling yourself?
        </question>

        <option1 name="quiz_8_1">Some programming skills</option1>
        <option2 name="quiz_8_2">Specific math knowledge</option2>
        <option3 name="quiz_8_3">None
        </option3>
        <answerNr>3</answerNr>
        <solution>But you need a high-school graduation though!</solution>
    </Question>

    <Question>
        <question name="quiz_question_9">What master can't be pursued after BINFO at Unilu?
        </question>

        <option1 name="quiz_9_1">Master in Information and Computer Sciences</option1>
        <option2 name="quiz_9_2">Master en Développement durable</option2>
        <option3 name="quiz_9_3">Master in Information System Security Management</option3>
        <answerNr>2</answerNr>
        <solution>Master en Développement durable is part of Engineering cursus.</solution>
    </Question>

    <Question>
        <question name="quiz_question_10">What is the main language used in class?</question>

        <option1 name="quiz_10_1">French</option1>
        <option2 name="quiz_10_2">English</option2>
        <option3 name="quiz_10_3">German</option3>
        <answerNr>2</answerNr>
        <solution>English, and it is the best option regarding the diversity of UNILU students in general. There are some classes in french too.</solution>
    </Question>

    <Question>
        <question name="quiz_question_11">Who is in charge of BINFO program?</question>

        <option1 name="quiz_11_1" translatable="false">Prof. Dr.Franck Leprévost</option1>
        <option2 name="quiz_11_2" translatable="false">Prof. Dr.Steffen Rothkugel</option2>
        <option3 name="quiz_11_3" translatable="false">Prof. Dr.Volker Müller</option3>
        <answerNr>3</answerNr>
        <solution>Prof. Dr.Müller is at the same time in charge of the program, and giving some classes in different semesters too.</solution>
    </Question>

    <Question>
        <question name="quiz_question_12">Who's BINFO's secretary?</question>

        <option1 name="quiz_12_1" translatable="false">Sandra Rosin</option1>
        <option2 name="quiz_12_2" translatable="false">Marielle Mabille</option2>
        <option3 name="quiz_12_3" translatable="false">Nicolas Guelfi</option3>
        <answerNr>1</answerNr>
        <solution>Her office is in the 6th floor of MSA (Maison du Savoir).</solution>
    </Question>

    <Question>
        <question name="quiz_question_13">When was the university founded?</question>

        <option1 name="quiz_13_1">Before 2000</option1>
        <option2 name="quiz_13_2">Between 2000 and 2010</option2>
        <option3 name="quiz_13_3">After 2010</option3>
        <answerNr>2</answerNr>
        <solution>It was founded the 12th August 2003. It is the only public university in Luxembourg.</solution>
    </Question>

    <Question>
        <question name="quiz_question_14">How many students are there in Unilu?
        </question>

        <option1 name="quiz_14_1" translatable="false">≈ 5000</option1>
        <option2 name="quiz_14_2" translatable="false">≈ 10000</option2>
        <option3 name="quiz_14_3" translatable="false">≈ 20000</option3>
        <answerNr>1</answerNr>
        <solution>Uni had 6400 students in 2017 and the number keeps increasing years after years.</solution>
    </Question>

    <Question>
        <question name="quiz_question_15">How many programs does the university propose (Bachelors and Masters)?
        </question>

        <option1 name="quiz_15_1">Less than 20</option1>
        <option2 name="quiz_15_2">More than 30</option2>
        <option3 name="quiz_15_3">Between 20 and 30</option3>
        <answerNr>2</answerNr>
        <solution>11 Bachelors and 23 Masters for a total of 34 study programs.</solution>
    </Question>

    <Question>
        <question name="quiz_question_16">How many faculties are there in Unilu?</question>

        <option1 name="quiz_16_1" translatable="false">3</option1>
        <option2 name="quiz_16_2" translatable="false">5</option2>
        <option3 name="quiz_16_3" translatable="false">10</option3>
        <answerNr>1</answerNr>
        <solution>Faculties of [Law, Economics and Finance] [Science, Technology and Medecine] [Humanities, Education and Social Sciences].</solution>
    </Question>

    <Question>
        <question name="quiz_question_17">What does LLC stand for?</question>

        <option1 name="quiz_17_1" translatable="false">Luxembourg Library Center</option1>
        <option2 name="quiz_17_2" translatable="false">Library Learning Center</option2>
        <option3 name="quiz_17_3" translatable="false">Luxembourg Learning Center</option3>
        <answerNr>3</answerNr>
        <solution>Inaugurated in 2018, LLC is offering so-called traditional library services as well as providing students with a state-of-the-art environment.</solution>
    </Question>

    <Question>
        <question name="quiz_question_18">How many countries/nationalities are represented in Unilu?
        </question>

        <option1 name="quiz_18_1" translatable="false">≈ 25</option1>
        <option2 name="quiz_18_2" translatable="false">≈ 50</option2>
        <option3 name="quiz_18_3" translatable="false">≈ 100</option3>
        <answerNr>3</answerNr>
        <solution>Unilu characteristic is its student diversity. Students come from border countries like France, Belgium and Germany as well as from many other countries.</solution>
    </Question>

    <Question>
        <question name="quiz_question_19">How many ECTS does the BINFO program contain?</question>

        <option1 name="quiz_19_1" translatable="false">90 ECTS</option1>
        <option2 name="quiz_19_2" translatable="false">120 ECTS</option2>
        <option3 name="quiz_19_3" translatable="false">180 ECTS</option3>
        <answerNr>3</answerNr>
        <solution>A total of 180 ECTS would make you graduate from University and give you access to Masters either in Unilu or other universities.</solution>
    </Question>
</questions>